services:
  - type: web
    name: apconect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn pi2025.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-secret
      - key: POSTGRES_DB
        fromDatabase:
          name: apconect-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: apconect-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: apconect-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: apconect-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: apconect-db
          property: port
