# Generated by Django 5.2 on 2025-04-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apconect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.CharField(choices=[('infra', 'Infraestrutura'), ('alimentos', 'Alimentos'), ('servicos', 'Serviços'), ('vendas', 'Vendas')], max_length=20),
        ),
    ]
